baseURL: https://x686.pro/
languageCode: en-us
title: private.space
theme: archie

pygmentsstyle: "solarized-dark"
pygmentscodefences: true
pygmentscodefencesguesssyntax: true

menu:
  main:
    - name: "root"
      url: "/"
      weight: 1
    - name: "thoughts"
      url: "/thoughts"
      weight: 2
    - name: "me"
      url: "/me"
      weight: 3

params:
  mode: light
  mathjax: true
  social:
    - name: "Github"
      icon: "github"
      url: "https://github.com/nukah"
    - name: "LinkedIn"
      icon: "linkedin"
      url: "https://linkedin.com/nukah"
