baseURL: https://x686.pro/
languageCode: en-us
title: private.space
theme: terminal

pygmentsstyle: "solarized-dark"
pygmentscodefences: true
pygmentscodefencesguesssyntax: true

menu:
  main:
    - name: "thoughts"
      url: "/thoughts"
      weight: 1
    - name: "links"
      url: "/links"
      weight: 2
    - name: "me"
      url: "/me"
      weight: 3

params:
  themeColor: purple
  showMenuItems: 5
  showLanguageSelector: false
  fullWidthTheme: false
  centerTheme: true
  showLastUpdated: true
  readingTime: true
  social:
    - name: "Github"
      icon: "github"
      url: "https://github.com/nukah"
    - name: "Email"
      icon: "email"
      url: "mailto:me@x686.pro"
