baseURL: https://x686.pro/
languageCode: en-us
title: mighty.private.space
theme: archie

pygmentsstyle: "catppuccin-frappe"
pygmentscodefences: true
pygmentscodefencesguesssyntax: true
enableGitInfo: true

menu:
  main:
    - name: "thoughts"
      url: "/thoughts"
      weight: 1
    - name: "links"
      url: "/links"
      weight: 2
    - name: "me"
      url: "/me"
      weight: 3

params:
  customcss:
    - css/686.css
  mode: light
  favicon: "/favicon.ico"
  showMenuItems: 5
  readingTime: true
  social:
    - name: "Github"
      icon: "github"
      url: "https://github.com/nukah"
    - name: "LinkedIn"
      icon: "linkedin"
      url: "https://www.linkedin.com/in/bgushin/"
    - name: "Email"
      icon: "at-sign"
      url: "mailto:me@x686.pro"

markup:
  tableOfContents:
    endLevel: 4
    ordered: false
    startLevel: 1